import { Suspense } from 'react'
import { IBM_Plex_Sans } from 'next/font/google'
import '../styles/globals.css'
import { Toaster } from 'react-hot-toast'
import { WalletProvider } from '@/context/Web3Context'
import type { Metadata } from 'next'

const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'rLoop GPU MARKETPLACE',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${ibm_plex_sans.className} antialiased`}>
        <WalletProvider>
          <Suspense>{children}</Suspense>
        </WalletProvider>
        <Toaster />
      </body>
    </html>
  )
}
